services:
  postgres:
    image: local/supabase-postgres:18-karval
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U supabase_admin -d postgres -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: supabase_admin
      POSTGRES_DB: postgres

    command:
      - postgres
      - -D
      - /etc/postgresql
      - -c
      - max_connections=500
      - -c
      - shared_buffers=3GB
      - -c
      - work_mem=128MB
      - -c
      - maintenance_work_mem=128MB
      - -c
      - log_min_messages=fatal
      - -c
      - listen_addresses=*
      - -c
      - shared_preload_libraries=pg_stat_statements,pgaudit,pg_cron,pg_net,pg_tle,safeupdate

    ports:
      - target: 5432
        published: 54318
        protocol: tcp
        mode: ingress

    volumes:
      - postgres18_data:/var/lib/postgresql/data

    networks:
      - portainer_agent_network

    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "2.5"
          memory: 2560M

volumes:
  postgres18_data:
    external: true
    name: postgres18_postgres18_data

networks:
  portainer_agent_network:
    external: true
    name: portainer_agent_network
